version: 2
jobs:
  build:
    working_directory: ~/imgfetcha
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          BUNDLER_VERSION: 2.1.4
  steps:
    - checkout

    - run:
        name: Install bundler
        command: gem install bundler
    - run:
        name: Install deps
        command: bundle install
