version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-buster
    steps:
      - checkout
      - run: bundle -v
      - run: ruby -v
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rspec
