version: 2
jobs:
    build:
        working_directory: ~/imgfetcha
        docker:
            - image: circleci/ruby:2.7.1
    steps:
        - checkout
        - run: gem install bundler -v 2.1.4
        - run: bundle install
